apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: eyalpross101/server
          env:
            - name: MONGO_URI
              value: "mongodb://server-mongo-srv:27017/server"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:  #get his value from kubernetes secret
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: server-srv
spec:
  selector:
    app: server
  ports:
    - name: server
      protocol: TCP
      port: 3000
      targetPort: 3000
