name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: |
            backend/server/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}  # detected changes in package-lock.json
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Verify directory exists
        run: ls -la backend/server 

      - name: Install dependencies and run tests
        run: |
          cd backend/server
          npm install
          npm run test:ci


